version: '3.2'
services:
    las:
        image: sconecuratedimages/iexecsgx:las
        devices:
         - "$SGX_DEVICE"
        command: las
        tty: true
        ports:
          - target: 18766
            published: 18766
            protocol: tcp
            mode: host
